# Generated by Django 4.2 on 2023-05-23 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
