# Generated by Django 4.2 on 2023-05-23 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('roll', models.CharField(max_length=254)),
                ('image', models.ImageField(upload_to='students')),
            ],
        ),
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='waste_type')),
            ],
        ),
        migrations.CreateModel(
            name='FoodWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('source', models.CharField(max_length=254)),
                ('where_to_throw', models.CharField(max_length=254)),
                ('image', models.ImageField(upload_to='food_waste')),
                ('time_to_decay', models.CharField(max_length=254)),
                ('carbon_footprint', models.CharField(max_length=254)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Waste.student')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Waste.wastetype')),
            ],
        ),
    ]
